import type { Metadata } from 'next';
import { Roboto_Condensed } from 'next/font/google';
import './styles/styles.scss';

const robotoCondensed = Roboto_Condensed({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Zara Web Chalenge',
  description: 'Generated by create next app',
};
import { LoadingProvider } from '@/contexts/LoadingContext';
import { FavoritesProvider } from '@/contexts/FavoritesContext';

export default function RootLayout({children}: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={robotoCondensed.className}>
        <LoadingProvider>
          <FavoritesProvider>
            {children}
          </FavoritesProvider>
        </LoadingProvider>
       </body>
    </html>
  );
}
