import type { Metadata } from 'next';
import { Roboto_Condensed } from 'next/font/google';
import './styles/globals.css';

const robotoCondensed = Roboto_Condensed({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Zara Web Chalenge',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={robotoCondensed.className}>{children}</body>
    </html>
  );
}
